#!/bin/bash
# Auto-generated by syft-widget - DO NOT EDIT
# This script starts the widget server for SyftBox integration

cd "$(dirname "$0")"

# Start the widget server
echo "Starting syft-widget server for happybird-watcher..."
python -m syft_widget.server \
    --package-name "happybird-watcher" \
    --package-dir "$(pwd)" \
    --auto-discover
